### ISSUE TITLE
Site inaccessible

### ISSUE THREAD

**Issue by kupoback** [aMoniker/wpbin#1]
When trying to access wpbin.io the site returns inaccessible as the site IP cannot be found

![Image of error](https://i.ibb.co/db0RvdM/Screen-Shot-2020-06-05-at-11-57-44.png)

**Comment by aMoniker** [comment]
Apologies for this. The domain should have auto-renewed, but there was a problem and I didn't catch it. This should be resolved soon.

**Comment by kupoback** [comment]
Excellent, thank you for checking into this! It seems to be working rather well. I'm sure it's not high on your priority list, but have you considered integrating SSL for the site?

**Comment by aMoniker** [comment]
To be honest, I've neglected this site, but I'm really happy to know that people still find it useful. I'll look into adding SSL and into making some sorely needed updates!

**Comment by kupoback** [comment]
Awesome! Thank you very much, was only curious is all! Much appreciated!
